name: dummymart
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  dio: ^5.3.3
  flextras: ^1.0.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.3
  flutter_native_splash: ^2.3.5
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  go_router: ^12.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hooks_riverpod: ^2.4.5
  json_annotation: ^4.8.1
  riverpod_annotation: ^2.3.0

dev_dependencies:
  build_runner: ^2.4.6
  change_app_package_name: ^1.1.0
  custom_lint: ^0.5.6
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  hive_generator: ^2.0.1
  husky: ^0.1.6
  json_serializable: ^6.7.1
  lint_staged: ^0.4.2
  riverpod_generator: ^2.3.5
  riverpod_lint: ^2.3.3

flutter:
  uses-material-design: true

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/splash.png
  android_12:
    icon_background_color: "#FFFFFF"
    image: assets/images/splash-android-12.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/launcher.png
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: assets/images/launcher-fg.png

lint_staged:
  'lib/**.dart': dart format --fix
